#!/usr/bin/env python3
"""Hash a private denylist into scripts/scrub-denylist.sha256 for the scrub guard.

    python3 scripts/scrub-hash.py private/scrub-denylist.txt

The input is one literal per line (# comments and blank lines ignored), kept out of git. The output holds only each
literal's length and the SHA-256 of its lowercase form, so the public repo never says what it is looking for (until
2026-10-02 the guard listed the literals themselves, which published the very values it was meant to keep out).
"""
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scrub-denylist.sha256"


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    literals = sorted({
        line.strip().lower()
        for line in Path(sys.argv[1]).read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    })
    lines = [f"{len(t.encode('utf-8'))} {hashlib.sha256(t.encode('utf-8')).hexdigest()}" for t in literals]
    OUT.write_text(
        "# Scrub guard denylist: <byte length> <sha256 of the lowercase literal>. Generated by scripts/scrub-hash.py\n"
        "# from a private list; never put the literals themselves in the repo.\n"
        + "\n".join(sorted(lines)) + "\n",
        encoding="utf-8",
    )
    print(f"{len(lines)} hashes written to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
